name: Send Project Version to Git-Custom-Badges

on:
  push:
    branches:
      - main

jobs:
  send_package_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Extract package.json fields
        id: extract
        run: |
          echo "::set-output name=name::$(node -p "require('./package.json').name")"
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Send Package Info to API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "project-push-token: ${{ secrets.GCB_PUSH_TOKEN_PROJECT }}" \
            -d '{"name": "${{ steps.extract.outputs.name }}", "version": "${{ steps.extract.outputs.version }}"}' \
            https://gcb.maxlehmann.dev/projects